# Generated by Django 4.0.3 on 2022-03-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
